import React from 'react';
import Head from 'next/head';

import { SearchBar } from '../SearchBar/index';
import { Header, Container } from './styled';
import PropTypes from 'prop-types';

export const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Meli App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header>
        <SearchBar />
      </Header>
      <Container>{children}</Container>
    </div>
  );
};

Layout.propTypes = {
  children: PropTypes.element,
};