import React, { useContext } from 'react';
import Head from 'next/head';

import { SearchBar } from '../SearchBar/index';
import Breadcrumb from '../BreadCrumb/index';
import { Header, Container } from './styled';

export const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Meli App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header>
        <SearchBar />
      </Header>
      <Container>
        {/* <Breadcrumb /> */}
        {children}
      </Container>
    </div>
  );
};
