import React, { useContext } from "react";
import Head from "next/head";
import { useState } from "react";
import AppContext from "../../context/AppContext";

import { SearchBar } from "../SearchBar/index";
import Breadcrumb from "../BreadCrumb/index";

export const Layout = ({ children }) => {
  const [query, setQuery] = useState();

  const { getItems } = useContext(AppContext);

  const handleSearchClick = () => {
    getItems(query);
  };

  const handleChange = (element) => {
    setQuery(element.target.value);
  };
  return (
    <div className="container">
      <Head>
        <title>Meli App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <SearchBar
          handleSearchClick={handleSearchClick}
          handleChange={handleChange}
        />
        <Breadcrumb />
        {children}
      </main>
    </div>
  );
};
